image: docker:stable-git

variables:
  CI_REGISTRY_IMAGE: "rlopezv/kubeedge-demo-app"
  CI_INFRA_REPO: "https://${GITLAB_USER_LOGIN}:${CI_ACCESS_TOKEN}@gitlab.com/ramon.lopez.viana/kubeedge-demo-infra.git"
  CI_INFRA_PATH: "kubeedge-demo-infra"

## Defined stages
stages:
  - build
  - test
  - publish

environment:
  stage: .pre 
  script:
    - printenv

build:
  image: docker:stable-dind
  stage: build
  before_script:
    - docker info
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} .
  rules:
    - when: never

build_kaniko:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    # - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - echo ${CI_DOCKER_AUTH_CONFIG} > /kaniko/.docker/config.json 
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  rules:
    - when: always

test:
  stage: test
  script:
    - echo 'tests should be here'

update_infra:
  stage: publish
  before_script:
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
  script:
    - git clone $CI_INFRA_REPO
    - cd $CI_INFRA_PATH
    - echo ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}@${CI_COMMIT_BEFORE_SHA} >> versions.txt
    - cat versions.txt
    - git add -A
    - git commit -m "Pushed from ${CI_PROJECT_URL} ${CI_COMMIT_REF_SLUG} ${CI_COMMIT_BEFORE_SHA}" 
    - git push $CI_INFRA_REPO
