apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeedge-app-deployment
  labels:
    app: kubeedge-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeedge-app
  template:
    metadata:
      labels:
        app: kubeedge-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/edge
                  operator: Exists
                - key: node-role.kubernetes.io/agent
                  operator: Exists    
      containers:
      - name: kubedge-app
        image: rlopezv/kubeedge-demo-app
        ports:
        - containerPort: 1080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubeedge-app
  name: kubeedge-app
spec:
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: kubeedge-app
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
#   labels:
#     name: nginx
# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       nodePort: 30080
#       name: http
#   selector:
#     name: nginx