apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeedge-app-deployment
  labels:
    app: kubeedge-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeedge-app
  template:
    metadata:
      labels:
        app: kubeedge-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/edge
                  operator: DoesNotExist
                - key: node-role.kubernetes.io/agent
                  operator: DoesNotExist    
      containers:
      - name: kubedge-app
        image: rlopezv/kubeedge-nginx-app-amd64
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: nginx-pod-port
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubeedge-app
  name: kubeedge-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: nginx-pod-port
      protocol: TCP
      name: http
      nodePort: 30007
  selector:
    app: kubeedge-app

