apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeedge-app
spec:
  destination:
    namespace: kubeedge-app
    server: https://kubernetes.default.svc
  project: kubeedge
  source:
    # path: manifests-kubeedge
    # repoURL: https://gitlab.com/ramon.lopez.viana/kubeedge-demo-infra.git
    # targetRevision: main
    path: nginx-infra/manifests-kubeedge
    repoURL: https://github.com/rlopezv/kubeedge-app.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true