apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeedge-app
  namespace: kubeedge-app
spec:
  destination:
    namespace: kubeedge-app
    server: https://kubernetes.default.svc
  project: kubedge-project
  source:
    path: manifests
    repoURL: https://gitlab.com/ramon.lopez.viana/kubeedge-demo-infra.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true